services:
  api:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    links: [ db ]

  db:
    image: mongo
    restart: always
    env_file:
      - .env
    # environment:

      # MONGO_INITDB_ROOT_USERNAME: mongo
      # MONGO_INITDB_ROOT_PASSWORD: secretpwd
    # volumes:
    #   - mongo_data:/data/db
    # networks:
    #   - blog-api
    ports: 
      - 27017:27017

networks:
  blog-api:
    driver: bridge
volumes:
  mongo_data:
    driver: local